version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      nx-packages:
        patterns:
          - "@nx/*"
      swc:
        patterns:
          - "@swc/*"
          - "@swc-node/*"
      typescript-eslint-packages:
        patterns:
          - "@typescript-eslint/*"
