services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - csfin:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=codescape
      - POSTGRES_DB=codescape-financial
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - "5432:5432"

volumes:
  csfin:
